export const MISC_SET_LOCALE = 'MISC_SET_LOCALE'
export const MISC_SET_META = 'MISC_SET_META'
export const MISC_SET_CONFIG = 'MISC_SET_CONFIG'
export const SYNC_TIME = 'SYNC_TIME'
export const SYNC_RESPONSE_TIME = 'SYNC_RESPONSE_TIME'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const SHOW_MENU = 'SHOW_MENU'
export const HIDE_MENU = 'HIDE_MENU'

export const SHOW_SIDE_MENU = 'SHOW_SIDE_MENU'
export const HIDE_SIDE_MENU = 'HIDE_SIDE_MENU'

export const ROUTER_BEFORE_NAVIGATE = 'ROUTER_BEFORE_NAVIGATE'
export const ROUTER_NAVIGATE = 'ROUTER_NAVIGATE'
export const ROUTER_ERROR_RAISE = 'ROUTER_ERROR_RAISE'
export const ROUTER_REJECTED = 'ROUTER_REJECTED'

export const USER_REQUEST_PENDING = 'USER_REQUEST_PENDING'
export const USER_REQUEST_FULFILLED = 'USER_REQUEST_FULFILLED'
export const USER_REQUEST_REJECTED = 'USER_REQUEST_REJECTED'

export const USER_DESTROY_PENDING = 'USER_DESTROY_PENDING'
export const USER_DESTROY_FULFILLED = 'USER_DESTROY_FULFILLED'
export const USER_DESTROY_REJECTED = 'USER_DESTROY_REJECTED'

export const SESSION_RESTORE = 'SESSION_RESTORE'
export const SESSION_DESTROY = 'SESSION_DESTROY'
export const SESSION_REQUEST_PENDING = 'SESSION_REQUEST_PENDING'
export const SESSION_REQUEST_FULFILLED = 'SESSION_REQUEST_FULFILLED'
export const SESSION_REQUEST_REJECTED = 'SESSION_REQUEST_REJECTED'

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING'
export const CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED'
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED'

export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS'
export const UPDATE_SEARCH_ADDRESS = 'UPDATE_SEARCH_ADDRESS'

export const CITIES_REQUEST_PENDING = 'CITIES_REQUEST_PENDING'
export const CITIES_REQUEST_FULFILLED = 'CITIES_REQUEST_FULFILLED'
export const CITIES_REQUEST_REJECTED = 'CITIES_REQUEST_REJECTED'

export const SEARCH_SITTERS_NOT_FOUND = 'SEARCH_SITTERS_PREFETCH'

export const SEARCH_SITTERS_PREFETCH = 'SEARCH_SITTERS_PREFETCH'
export const SEARCH_SITTERS_PREFETCH_PENDING = 'SEARCH_SITTERS_PREFETCH_PENDING'
export const SEARCH_SITTERS_PREFETCH_FULFILLED = 'SEARCH_SITTERS_PREFETCH_FULFILLED'
export const SEARCH_SITTERS_PREFETCH_REJECTED = 'SEARCH_SITTERS_PREFETCH_REJECTED'

export const SEARCH_SITTERS_REQUEST = 'SEARCH_SITTERS_REQUEST'
export const SEARCH_SITTERS_REQUEST_PENDING = 'SEARCH_SITTERS_REQUEST_PENDING'
export const SEARCH_SITTERS_REQUEST_FULFILLED = 'SEARCH_SITTERS_REQUEST_FULFILLED'
export const SEARCH_SITTERS_REQUEST_REJECTED = 'SEARCH_SITTERS_REQUEST_REJECTED'

export const SET_CONVERSATIONS_SEGMENT = 'SET_CONVERSATIONS_SEGMENT'

export const CONVERSATIONS_REQUEST_PENDING = 'CONVERSATIONS_REQUEST_PENDING'
export const CONVERSATIONS_REQUEST_FULFILLED = 'CONVERSATIONS_REQUEST_FULFILLED'
export const CONVERSATIONS_REQUEST_REJECTED = 'CONVERSATIONS_REQUEST_REJECTED'

export const CONVERSATION_REQUEST_PENDING = 'CONVERSATION_REQUEST_PENDING'
export const CONVERSATION_REQUEST_FULFILLED = 'CONVERSATION_REQUEST_FULFILLED'
export const CONVERSATION_REQUEST_REJECTED = 'CONVERSATION_REQUEST_REJECTED'

export const CONVERSATION_CREATE = 'CONVERSATION_CREATE'
export const CONVERSATION_CONNECT = 'CONVERSATION_CONNECT'
export const CONVERSATION_DISCONNECT = 'CONVERSATION_DISCONNECT'
export const CONVERSATION_MARK_STICKY = 'CONVERSATION_MARK_STICKY'

export const CONVERSATION_MARK_READ_PENDING = 'CONVERSATION_MARK_READ_PENDING'
export const CONVERSATION_MARK_READ_FULFILLED = 'CONVERSATION_MARK_READ_FULFILLED'
export const CONVERSATION_MARK_READ_REJECTED = 'CONVERSATION_MARK_READ_REJECTED'

export const MESSAGES_REQUEST = 'MESSAGES_REQUEST'
export const MESSAGES_REQUEST_PENDING = 'MESSAGES_REQUEST_PENDING'
export const MESSAGES_REQUEST_FULFILLED = 'MESSAGES_REQUEST_FULFILLED'
export const MESSAGES_REQUEST_REJECTED = 'MESSAGES_REQUEST_REJECTED'

export const FAYE_TRANSPORT_DOWN = 'FAYE_TRANSPORT_DOWN'
export const FAYE_TRANSPORT_UP = 'FAYE_TRANSPORT_UP'

export const INCOMING_CONVERSATION = 'INCOMING_CONVERSATION'

export const MESSAGE_CREATE = 'MESSAGE_CREATE'
export const MESSAGE_CREATE_PENDING = 'MESSAGE_CREATE_PENDING'
export const MESSAGE_CREATE_FULFILLED = 'MESSAGE_CREATE_FULFILLED'
export const MESSAGE_CREATE_REJECTED = 'MESSAGE_CREATE_REJECTED'

export const SITTER_REQUEST_PENDING = 'SITTER_REQUEST_PENDING'
export const SITTER_REQUEST_FULFILLED = 'SITTER_REQUEST_FULFILLED'
export const SITTER_REQUEST_REJECTED = 'SITTER_REQUEST_REJECTED'

export const SITTER_REVIEWS_PENDING = 'SITTER_REVIEWS_PENDING'
export const SITTER_REVIEWS_FULFILLED = 'SITTER_REVIEWS_FULFILLED'
export const SITTER_REVIEWS_REJECTED = 'SITTER_REVIEWS_REJECTED'

export const PARENT_REVIEWS_PENDING = 'PARENT_REVIEWS_PENDING'
export const PARENT_REVIEWS_FULFILLED = 'PARENT_REVIEWS_FULFILLED'
export const PARENT_REVIEWS_REJECTED = 'PARENT_REVIEWS_REJECTED'

export const PARTICIPANT_REQUEST_PENDING = 'PARTICIPANT_REQUEST_PENDING'
export const PARTICIPANT_REQUEST_FULFILLED = 'PARTICIPANT_REQUEST_FULFILLED'
export const PARTICIPANT_REQUEST_REJECTED = 'PARTICIPANT_REQUEST_REJECTED'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PHONE = 'EDIT_PHONE'

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING'
export const UPDATE_PROFILE_FULFILLED = 'UPDATE_PROFILE_FULFILLED'
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED'

export const UPDATE_SCHEDULE_PENDING = 'UPDATE_SCHEDULE_PENDING'
export const UPDATE_SCHEDULE_FULFILLED = 'UPDATE_SCHEDULE_FULFILLED'
export const UPDATE_SCHEDULE_REJECTED = 'UPDATE_SCHEDULE_REJECTED'

export const PHONE_VERIFICATION = 'PHONE_VERIFICATION'
export const PHONE_VERIFICATION_PENDING = 'PHONE_VERIFICATION_PENDING'
export const PHONE_VERIFICATION_FULFILLED = 'PHONE_VERIFICATION_FULFILLED'
export const PHONE_VERIFICATION_REJECTED = 'PHONE_VERIFICATION_REJECTED'

export const PHONE_CONFIRMATION_PENDING = 'PHONE_CONFIRMATION_PENDING'
export const PHONE_CONFIRMATION_FULFILLED = 'PHONE_CONFIRMATION_FULFILLED'
export const PHONE_CONFIRMATION_REJECTED = 'PHONE_CONFIRMATION_REJECTED'

export const DELETE_AVATAR_PENDING = 'DELETE_AVATAR_PENDING'
export const DELETE_AVATAR_FULFILLED = 'DELETE_AVATAR_FULFILLED'
export const DELETE_AVATAR_REJECTED = 'DELETE_AVATAR_REJECTED'

export const APPEND_AVATAR_IDS = 'APPEND_AVATAR_IDS'
export const ADD_AVATAR = 'ADD_AVATAR'

export const COMPLETE_REGISTRATION_PENDING = 'COMPLETE_REGISTRATION_PENDING'
export const COMPLETE_REGISTRATION_FULFILLED = 'COMPLETE_REGISTRATION_FULFILLED'
export const COMPLETE_REGISTRATION_REJECTED = 'COMPLETE_REGISTRATION_REJECTED'

export const FETCH_REQUESTS_PENDING = 'FETCH_REQUESTS_PENDING'
export const FETCH_REQUESTS_FULFILLED = 'FETCH_REQUESTS_FULFILLED'
export const FETCH_REQUESTS_REJECTED = 'FETCH_REQUESTS_REJECTED'

export const REQUEST_CREATE_PENDING = 'REQUEST_CREATE_PENDING'
export const REQUEST_CREATE_FULFILLED = 'REQUEST_CREATE_FULFILLED'
export const REQUEST_CREATE_REJECTED = 'REQUEST_CREATE_REJECTED'

export const REQUEST_ACCEPT_PENDING = 'REQUEST_ACCEPT_PENDING'
export const REQUEST_ACCEPT_FULFILLED = 'REQUEST_ACCEPT_FULFILLED'
export const REQUEST_ACCEPT_REJECTED = 'REQUEST_ACCEPT_REJECTED'

export const REQUEST_DECLINE_PENDING = 'REQUEST_DECLINE_PENDING'
export const REQUEST_DECLINE_FULFILLED = 'REQUEST_DECLINE_FULFILLED'
export const REQUEST_DECLINE_REJECTED = 'REQUEST_DECLINE_REJECTED'

export const REQUEST_CANCEL_PENDING = 'REQUEST_CANCEL_PENDING'
export const REQUEST_CANCEL_FULFILLED = 'REQUEST_CANCEL_FULFILLED'
export const REQUEST_CANCEL_REJECTED = 'REQUEST_CANCEL_REJECTED'

export const REQUEST_REJECT_PENDING = 'REQUEST_REJECT_PENDING'
export const REQUEST_REJECT_FULFILLED = 'REQUEST_REJECT_FULFILLED'
export const REQUEST_REJECT_REJECTED = 'REQUEST_REJECT_REJECTED'

export const REQUEST_ACTUAL_PENDING = 'REQUEST_ACTUAL_PENDING'
export const REQUEST_ACTUAL_FULFILLED = 'REQUEST_ACTUAL_FULFILLED'
export const REQUEST_ACTUAL_REJECTED = 'REQUEST_ACTUAL_REJECTED'

export const REQUEST_REVIEW_PENDING = 'REQUEST_REVIEW_PENDING'
export const REQUEST_REVIEW_FULFILLED = 'REQUEST_REVIEW_FULFILLED'
export const REQUEST_REVIEW_REJECTED = 'REQUEST_REVIEW_REJECTED'

export const ANNOUNCEMENT_PATCH = 'ANNOUNCEMENT_PATCH'

export const ANNOUNCEMENT_CREATE_PENDING = 'ANNOUNCEMENT_CREATE_PENDING'
export const ANNOUNCEMENT_CREATE_FULFILLED = 'ANNOUNCEMENT_CREATE_FULFILLED'
export const ANNOUNCEMENT_CREATE_REJECTED = 'ANNOUNCEMENT_CREATE_REJECTED'

export const ADD_CARD_PENDING = 'ADD_CARD_PENDING'
export const ADD_CARD_FULFILLED = 'ADD_CARD_FULFILLED'
export const ADD_CARD_REJECTED = 'ADD_CARD_REJECTED'

export const DELETE_CARD_PENDING = 'DELETE_CARD_PENDING'
export const DELETE_CARD_FULFILLED = 'DELETE_CARD_FULFILLED'
export const DELETE_CARD_REJECTED = 'DELETE_CARD_REJECTED'

export const FETCH_CARD_PENDING = 'FETCH_CARD_PENDING'
export const FETCH_CARD_FULFILLED = 'FETCH_CARD_FULFILLED'
export const FETCH_CARD_REJECTED = 'FETCH_CARD_REJECTED'

export const FETCH_SUBSCRIPTION_PENDING = 'FETCH_SUBSCRIPTION_PENDING'
export const FETCH_SUBSCRIPTION_FULFILLED = 'FETCH_SUBSCRIPTION_FULFILLED'
export const FETCH_SUBSCRIPTION_REJECTED = 'FETCH_SUBSCRIPTION_REJECTED'

export const CANCEL_SUBSCRIPTION_PENDING = 'CANCEL_SUBSCRIPTION_PENDING'
export const CANCEL_SUBSCRIPTION_FULFILLED = 'CANCEL_SUBSCRIPTION_FULFILLED'
export const CANCEL_SUBSCRIPTION_REJECTED = 'CANCEL_SUBSCRIPTION_REJECTED'

export const CREATE_SUBSCRIPTION_PENDING = 'CREATE_SUBSCRIPTION_PENDING'
export const CREATE_SUBSCRIPTION_FULFILLED = 'CREATE_SUBSCRIPTION_FULFILLED'
export const CREATE_SUBSCRIPTION_REJECTED = 'CREATE_SUBSCRIPTION_REJECTED'

export const FETCH_RECEIPTS_PENDING = 'FETCH_RECEIPTS_PENDING'
export const FETCH_RECEIPTS_FULFILLED = 'FETCH_RECEIPTS_FULFILLED'
export const FETCH_RECEIPTS_REJECTED = 'FETCH_RECEIPTS_REJECTED'

export const ANNOUNCEMENTS_FETCH_PENDING = 'ANNOUNCEMENTS_FETCH_PENDING'
export const ANNOUNCEMENTS_FETCH_FULFILLED = 'ANNOUNCEMENTS_FETCH_FULFILLED'
export const ANNOUNCEMENTS_FETCH_REJECTED = 'ANNOUNCEMENTS_FETCH_REJECTED'

export const ANNOUNCEMENT_CANCEL_PENDING = 'ANNOUNCEMENT_CANCEL_PENDING'
export const ANNOUNCEMENT_CANCEL_FULFILLED = 'ANNOUNCEMENT_CANCEL_FULFILLED'
export const ANNOUNCEMENT_CANCEL_REJECTED = 'ANNOUNCEMENT_CANCEL_REJECTED'

export const CREATE_ANNOUNCEMENT_RESPONSE_PENDING = 'CREATE_ANNOUNCEMENT_RESPONSE_PENDING'
export const CREATE_ANNOUNCEMENT_RESPONSE_FULFILLED = 'CREATE_ANNOUNCEMENT_RESPONSE_FULFILLED'
export const CREATE_ANNOUNCEMENT_RESPONSE_REJECTED = 'CREATE_ANNOUNCEMENT_RESPONSE_REJECTED'

export const CANCEL_ANNOUNCEMENT_RESPONSE_PENDING = 'CANCEL_ANNOUNCEMENT_RESPONSE_PENDING'
export const CANCEL_ANNOUNCEMENT_RESPONSE_FULFILLED = 'CANCEL_ANNOUNCEMENT_RESPONSE_FULFILLED'
export const CANCEL_ANNOUNCEMENT_RESPONSE_REJECTED = 'CANCEL_ANNOUNCEMENT_RESPONSE_REJECTED'

export const DECLINE_ANNOUNCEMENT_RESPONSE_PENDING = 'DECLINE_ANNOUNCEMENT_RESPONSE_PENDING'
export const DECLINE_ANNOUNCEMENT_RESPONSE_FULFILLED = 'DECLINE_ANNOUNCEMENT_RESPONSE_FULFILLED'
export const DECLINE_ANNOUNCEMENT_RESPONSE_REJECTED = 'DECLINE_ANNOUNCEMENT_RESPONSE_REJECTED'

export const CREATE_REQUEST_FROM_ANNOUNCEMENT_RESPONSE_PENDING = 'CREATE_REQUEST_FROM_ANNOUNCEMENT_RESPONSE_PENDING'
export const CREATE_REQUEST_FROM_ANNOUNCEMENT_RESPONSE_FULFILLED = 'CREATE_REQUEST_FROM_ANNOUNCEMENT_RESPONSE_FULFILLED'
export const CREATE_REQUEST_FROM_ANNOUNCEMENT_RESPONSE_REJECTED = 'CREATE_REQUEST_FROM_ANNOUNCEMENT_RESPONSE_REJECTED'

export const FAVORITES_PENDING = 'FAVORITES_PENDING'
export const FAVORITES_FULFILLED = 'FAVORITES_FULFILLED'
export const FAVORITES_REJECTED = 'FAVORITES_REJECTED'

export const ADD_TO_FAVORITES_PENDING = 'ADD_TO_FAVORITES_PENDING'
export const ADD_TO_FAVORITES_FULFILLED = 'ADD_TO_FAVORITES_FULFILLED'
export const ADD_TO_FAVORITES_REJECTED = 'ADD_TO_FAVORITES_REJECTED'

export const DELETE_FROM_FAVORITES_PENDING = 'DELETE_FROM_FAVORITES_PENDING'
export const DELETE_FROM_FAVORITES_FULFILLED = 'DELETE_FROM_FAVORITES_FULFILLED'
export const DELETE_FROM_FAVORITES_REJECTED = 'DELETE_FROM_FAVORITES_REJECTED'

export const POST_SCHOOL_REQUEST_PENDING = 'POST_SCHOOL_REQUEST_PENDING'
export const POST_SCHOOL_REQUEST_FULFILLED = 'POST_SCHOOL_REQUEST_FULFILLED'
export const POST_SCHOOL_REQUEST_REJECTED = 'POST_SCHOOL_REQUEST_REJECTED'

export const FETCH_PROMOCODES_PENDING = 'FETCH_PROMOCODES_PENDING'
export const FETCH_PROMOCODES_FULFILLED = 'FETCH_PROMOCODES_FULFILLED'
export const FETCH_PROMOCODES_REJECTED = 'FETCH_PROMOCODES_REJECTED'

export const APPLY_PROMOCODE_PENDING = 'APPLY_PROMOCODE_PENDING'
export const APPLY_PROMOCODE_FULFILLED = 'APPLY_PROMOCODE_FULFILLED'
export const APPLY_PROMOCODE_REJECTED = 'APPLY_PROMOCODE_REJECTED'
