export const MISC_SET_LOCALE = 'MISC_SET_LOCALE'
export const MISC_SET_CONFIG = 'MISC_SET_CONFIG'
export const SYNC_TIME = 'SYNC_TIME'
export const SYNC_RESPONSE_TIME = 'SYNC_RESPONSE_TIME'

export const ROUTER_BEFORE_NAVIGATE = 'ROUTER_BEFORE_NAVIGATE'
export const ROUTER_NAVIGATE = 'ROUTER_NAVIGATE'
export const ROUTER_ERROR_RAISE = 'ROUTER_ERROR_RAISE'
export const ROUTER_REJECTED = 'ROUTER_REJECTED'
